<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.SfGrid.WPF" Version="29.2.11" />

	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SfDatagrid.WPF.Extensions\SfDatagrid.WPF.Extensions.csproj" />
  </ItemGroup>

</Project>
